Separate validations for event types, add salesforce
Use the pattern properties as a generic object with multiple keys with each key denoting a particular event type. Hence separating out validations for kafka and http. For example, kafka will not need a params section as per my current understanding. Added salesforce event type too.

Tested with the following validations:

```
abc.kafka1.def:
  # a new message arrives on the topic_name
  id: /kafkaWebhook
  fn: com.jfs.publish_kafka #The event handler written in publish_kafka.yml, and
  # kept in src/workflows/com/jfs folder (in this example)
  on_validation_error: 'foo'
  # kept in src/workflows/com/jfs folder (in this example)
  body:
    description: The body of the query
    content:
      application/json: # For ex. application/json application/xml
        schema:
          type: object
          properties:
            name:
              type: string
          required: [name]
```
and for salesforce
```
topic_name.salesforce8.datasourceName:
  id: /salesforcetopic
  fn: com.jfs.handle_title_events
  on_validation_error: com.jfs.handle_validation_error
  body:
    description: The body of the query
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
          required: [name]
```
and an http event too
```
/event-endpoint.http.put:
  summary: 'summary of the event'
  description: 'description of the event'
  fn: 'full path of the function, seprated with dots, remove .yaml, like: com.biz.helloworld'
  authn: true
  on_validation_error: 'foo'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object

```